### ISSUE TITLE
Gateway software ?

### ISSUE THREAD

**Issue by joelguittet** [Sub-IoT/Sub-IoT-Stack#109]
Hello,

I'm interested on DASH7, but it seems this repository is only about the End Device side, right ?

Is there any repository or ressource for the gateway hardware and software as well ? I know the WizziGate (https://wizzilab.com/wiki/#!wizzikit/../hardware/wizzigate_wrt.md) but I haven't found any other solution to build the gateway and server side...

I'm looking for something like LoRaWAN for example, on which there are several solutions to build a gateway and there are also several open-source or closed servers. In my opinion this highly participate to the adoption of the standard... To be more accurate I would like to add DASH7 gateway capability to an existing product. Best solution for me is mini-pcie cards and in any case I'm not interested by the WizziGate solution.

Thanks for any feedbacks!
Joel

**Comment by LOorts-Aloxy** [comment]
Hi Joel!
This repository is aimed at both sides. If you take a look at the examples, you can find [a gateway application](https://github.com/Sub-IoT/Sub-IoT-Stack/tree/master/stack/apps/gateway).

This gateway application will receive all D7 messages and forward them to the serial port of your device. To actually receive the messages on another operating system, you can use the [pyd7a repository](https://github.com/Sub-IoT/pyd7a) that is included in our Organization. 
pyd7a can be used to receive the serial messages and for example forward them over MQTT as in the [Sensor Push Led](https://github.com/Sub-IoT/pyd7a/blob/master/examples/sensor_push_led.py) and [modem2mqtt](https://github.com/Sub-IoT/pyd7a/blob/master/tools/modem2mqtt.py) examples.

At the moment, there are no D7-modules available using the mini-pcie interface. The board where this repository will work best on, is the [B-L072-LRWAN1](https://www.st.com/en/evaluation-tools/b-l072z-lrwan1.html), but it is very easily ported to another device using the same Murata chip. The gateway software can also easily be run on a constrained system, we have tested it on a Raspberry Pi numbers of times without any problems.

Hope this paints a clear picture and excites you for the project!

Liam
