### ISSUE TITLE
Performance results available?

### ISSUE THREAD

**Issue by aitorzabala** [Sub-IoT/Sub-IoT-Stack#112]
Hi,

I am looking forward to experiment with DASH7 for an industrial use case, however in the README it states the following:

> "This implementation focuses on completeness, correctness, ease of use and understanding. Performance and code size are less important aspects."

What is the performance that we should be expecting (in terms of bps/delay of nodes/gateways or even number of supported devices)? Are there any publicly available results?

Best regards,

**Comment by glennergeerts** [comment]
Hi, welcome to the project!

If I understand correctly you are mostly looking into network scalability and throughput? As far as I know there are no extensive results yet. The supported bit-rates are listed in the spec. Delay and effective throughput depends more on your environment (noise, collisions, ...) so this can only be validated in simulation or real life. There is no technical restriction in terms of number of nodes per gateway. Scalability is more limited here by number of messages (regardless of number of devices) and local RF regulations (eg duty cycle restrictions). So there is no easy response to your question imo, a lot depends on the application.
