### ISSUE TITLE
Some compiler flags that cause errors now that might be worth it to be fixed

### ISSUE THREAD

**Issue by ijager** [Sub-IoT/Sub-IoT-Stack#122]
Since all warnings are now treated as errors, the following warnings will cause compile errors and can not be used until the stack fixes these (minor) issues:

- `"-Wshadow"`
- `"-Wextra"` which results in: `-Werror=sign-compare` errors

**Comment by JFinneganAloxy** [comment]
Thanks for highlighting this, fixing this now.

**Comment by JFinneganAloxy** [comment]
These compiler flags have been added (and minor issues fixed).
