### ISSUE TITLE
Transmitted frequency is occasionally 2 MHz off

### ISSUE THREAD

**Issue by rith87** [Sub-IoT/Sub-IoT-Stack#16]
Hello folks,

I have a custom board that uses the Dash 7 stack on the master branch. The board works most of the time and TX/RX is fine. However, there are occasions where the TX frequency is ~435 MHz instead of 433 MHz and hence my receiver is unable to pick up the transmission. I was thinking that it was a hardware issue but I don't hit this problem with the sample 433 MHz configuration in the Smart RF studio. I tried replicating some of the registers (replicating the full set caused a hang somehow... my guess is because of the rising/falling edges in the interrupt handler) from the Smart RF studio but the transmitted frequency was still 435 MHz (http://e2e.ti.com/cfs-file.ashx/__key/communityserver-discussions-components-files/228/7888.no_5F00_rx.png).

Has anyone else hit this issue? I really hope that I won't have to switch to Simpliciti :(

**Comment by LOorts-Aloxy** [comment]
There have been major changes to the open source stack in the meantime, and no comments on this issue. Assuming this is fixed for now. If this issue is not fixed, do not hesitate to re-open the issue.
